### ISSUE TITLE
session name or tags not work

### ISSUE THREAD

**Issue by SaikaQH** [MamoruDS/shell-notify-telegram-bot#4]
I use command "notify -t xxx_sss -s xx_sss --silent". but no notice send to my telegram

**Comment by MamoruDS** [comment]
Thanks for reporting this issue.
It seems that tags are not "markdown safe" for [telegram API](https://core.telegram.org/bots/api#markdownv2-style), this issue will be fixed in the next release.

**Comment by MamoruDS** [comment]
This issue is fixed now.
